---
- name: Get vector distrib for Debian/Ubuntu
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector_{{ vector_version }}-1_amd64.deb"
    dest: "/tmp/vector-{{ vector_version }}.deb"
    mode: '0644'
  when: ansible_facts["os_family"] == "Debian"
  tags:
    - vector
    - distr

- name: Get vector distrib for RedHat/Oracle
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.x86_64.rpm"
    dest: "/tmp/vector-{{ vector_version }}.rpm"
    mode: '0644'
  when: ansible_facts["os_family"] == "RedHat"
  tags:
    - vector
    - distr

- name: Update apt cache for Debian/Ubuntu
  ansible.builtin.apt:
    update_cache: true
  when: ansible_facts["os_family"] == "Debian"
  tags:
    - vector
    - distr

- name: Install vector on Debian/Ubuntu
  ansible.builtin.apt:
    deb: "/tmp/vector-{{ vector_version }}.deb"
    state: present
  when: ansible_facts["os_family"] == "Debian"
  tags:
    - vector
    - distr

- name: Install vector on RedHat/Oracle
  ansible.builtin.yum:
    name: "/tmp/vector-{{ vector_version }}.rpm"
    state: present
    disable_gpg_check: true
  when: ansible_facts["os_family"] == "RedHat"
  tags:
    - vector
    - distr

- name: Start vector service
  ansible.builtin.service:
    name: vector
    state: restarted
  tags:
    - vector
    - restartservice
